services:
    auth.provider.oauth.service.battlenetus:
        class: ajhenderson\battlenet_oauth_us\auth\provider\oauth\service\battlenetus
        arguments:
            - @config
            - @request
        tags:
            - { name: auth.provider.oauth.service }