services:
    auth.provider.oauth.service.battlenetus:
        class: AJHenderson\BattleNetOAuthUS\auth\provider\oauth\service\battlenet_us
        arguments:
            - @config
            - @request
            - @user
        tags:
            - { name: auth.provider.oauth.service }
    auth.provider.oauth.service.battleneteu:
        class: AJHenderson\BattleNetOAuthUS\auth\provider\oauth\service\battlenet_eu
        arguments:
            - @config
            - @request
            - @user
        tags:
            - { name: auth.provider.oauth.service }
